#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-mongo_mapper
Version  : 0.13.1
Release  : 4
URL      : https://rubygems.org/downloads/mongo_mapper-0.13.1.gem
Source0  : https://rubygems.org/downloads/mongo_mapper-0.13.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-mongo_mapper-bin
BuildRequires : ruby
BuildRequires : rubygem-activemodel
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-rdoc

%description
= MongoMapper
{<img src="https://badge.fury.io/rb/mongo_mapper.png" alt="RubyGem" />}[https://rubygems.org/gems/mongo_mapper]
{<img src="https://travis-ci.org/mongomapper/mongomapper.png?branch=master" alt="Build Status" />}[https://travis-ci.org/mongomapper/mongomapper]
{<img src="https://coveralls.io/repos/jnunemaker/mongomapper/badge.png" alt="Coverage Status" />}[https://coveralls.io/r/jnunemaker/mongomapper]

%package bin
Summary: bin components for the rubygem-mongo_mapper package.
Group: Binaries

%description bin
bin components for the rubygem-mongo_mapper package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n mongo_mapper-0.13.1
gem spec %{SOURCE0} -l --ruby > rubygem-mongo_mapper.gemspec

%build
gem build rubygem-mongo_mapper.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
mongo_mapper-0.13.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/mongo_mapper-0.13.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/UPGRADES
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/bin/mmconsole
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/attr_accessible.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/attr_protected.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/cache_key.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/custom_types.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/identity_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/identity_map/automatic.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/modifiers/set.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/plugins.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/querying.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/safe.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/scopes.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/examples/validating/embedded_docs.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connections/10gen.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/connections/moped.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/embedded_document.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/binary.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/boolean.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/float.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/integer.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/kernel.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/nil_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/object_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/ordered_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/set.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/extensions/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/locale/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/middleware/identity_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/accessible.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/active_model.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/belongs_to_association.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/belongs_to_polymorphic_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/belongs_to_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/embedded_collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/in_array_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/many_association.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/many_documents_as_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/many_documents_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/many_embedded_polymorphic_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/many_embedded_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/many_polymorphic_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/one_as_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/one_association.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/one_embedded_polymorphic_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/one_embedded_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/one_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/associations/single_association.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/caching.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/clone.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/counter_cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dirty.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dumpable.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dynamic_querying.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/dynamic_querying/dynamic_finder.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/embedded_callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/embedded_document.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/equality.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/identity_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/indexes.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/inspect.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/keys/key.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/modifiers.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/pagination.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/persistence.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/protected.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/querying/decorated_plucky_query.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/rails/active_record_association_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/safe.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/sci.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/scopes.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/serialization.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/stats.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/timestamps.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/touch.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/userstamps.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/validations.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/railtie/database.rake
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/translation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/rails/generators/mongo_mapper/config/config_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/rails/generators/mongo_mapper/config/templates/mongo.yml
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/rails/generators/mongo_mapper/model/model_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/lib/rails/generators/mongo_mapper/model/templates/model.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/accessible_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/belongs_to_polymorphic_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/belongs_to_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/in_array_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/many_documents_as_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/many_documents_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/many_embedded_polymorphic_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/many_embedded_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/many_polymorphic_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/one_as_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/one_embedded_polymorphic_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/one_embedded_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations/one_proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/associations_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/binary_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/caching_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/callbacks_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/counter_cache_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/dirty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/document_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/dumpable_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/dynamic_querying_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/embedded_document_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/equality_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/extensions_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/identity_map_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/indexes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/keys_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/logger_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/modifiers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/pagination_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/protected_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/querying_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/rails_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/safe_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/sci_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/scopes_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/stats_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/timestamps_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/touch_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/userstamps_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/functional/validations_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/quality_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/support/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/support/models.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/associations/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/associations/belongs_to_association_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/associations/many_association_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/associations/one_association_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/associations/proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/clone_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/config_generator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/document_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/dynamic_finder_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/embedded_document_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/equality_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/exceptions_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/extensions_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/identity_map_middleware_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/inspect_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/key_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/keys_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/model_generator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/mongo_mapper_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/pagination_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/plugins_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/rails_compatibility_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/rails_reflect_on_association_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/rails_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/serialization_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/serializers/json_serializer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/serializers/xml_serializer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/time_zones_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/translation_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/mongo_mapper-0.13.1/spec/unit/validations_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/mongo_mapper-0.13.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/mmconsole
